project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("textsummy.urls",namespace="summy")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

textsummy/urls.py
from django.urls import path
from textsummy.views import *

app_name = "textsummy"

urlpatterns = [
    path(""              ,HomePageView.as_view()         ,name="home" ),
    path("text-summary/" ,TextSummaryPageView.as_view()  ,name="text" ),
    path("pdf-summary/"  ,PdfSummaryPageView.as_view()   ,name="pdf"  ),
    path("video-summary/",VideoSummaryPageView.as_view() ,name="video"),
    path("url-summary/"  ,UrlSummaryPageView.as_view()   ,name="url"  ),
]

textsummy/models.py
from django.db import models

# Create your models here.

textsummy/forms.py
from django import forms

class TextSummaryForm(forms.Form):
    text_summary = forms.CharField(widget=forms.Textarea)
    
class PDFSummaryForm(forms.Form):
    pdf_summary = forms.FileField()
    

textsummy/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,FormView
# from .spacy_summarization import text_summarizer
from .nltk_summarization import nltk_summarizer
from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.lex_rank import LexRankSummarizer
from transformers import T5Tokenizer, T5ForConditionalGeneration,pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.pipeline import make_pipeline
from django.core.files.storage import default_storage
from bs4 import BeautifulSoup
from urllib.request import urlopen
from textsummy.models import *
from django.conf import settings
from .forms import *
import spacy
import PyPDF2
from sumy.summarizers.text_rank import TextRankSummarizer

# Sumy 
def sumy_doc_summary(docx):
	parser = PlaintextParser.from_string(docx,Tokenizer("english"))
	lex_summarizer = LexRankSummarizer()
	summary = lex_summarizer(parser.document,3)
	summary_list = [str(sentence) for sentence in summary]
	result = ' '.join(summary_list)
	return result

def summy_summary(text):
    parser = PlaintextParser.from_string(text, Tokenizer('english'))
    summarizer = TextRankSummarizer()
    summarizer.stop_words = ['in', 'the', 'and', 'but', 'a', 'an']
    summary = summarizer(parser.document, sentences_count=10)
    summary_text = [str(sentence) for sentence in summary]
    return ' '.join(summary_text)
 
def spaacy_summary(input_text, num_sentences=30):
    # Load the Spacy model
    nlp = spacy.load('en_core_web_sm')

    # Process the input text
    doc = nlp(input_text)

    # Get the sentences and their corresponding scores
    sentence_scores = {}
    for sent in doc.sents:
        sentence_scores[sent] = sent.similarity(doc)

    # Sort the sentences by score and get the top `num_sentences`
    top_sentences = sorted(sentence_scores, key=sentence_scores.get, reverse=True)[:num_sentences]

    # Join the top sentences to create the summary
    summary = ' '.join([sent.text for sent in top_sentences])

    return summary
 
# Reading Time
def readingTime(mytext):
	total_words = len([ token.text for token in nlp(mytext)])
	estimatedTime = total_words/200.0
	return estimatedTime

# Fetch Text From Url
def get_text(url):
	page = urlopen(url)
	soup = BeautifulSoup(page)
	fetched_text = ' '.join(map(lambda p:p.text,soup.find_all('p')))
	return fetched_text

# Define a function to generate a summary
def generate_summary(text):
    # Initialize the model and tokenizer
    model_name = 't5-small'
    tokenizer = T5Tokenizer.from_pretrained(model_name)
    model = T5ForConditionalGeneration.from_pretrained(model_name)
    input_ids = tokenizer.encode(text, return_tensors='pt')

    # Generate a summary
    summary_ids = model.generate(input_ids, num_beams=4, max_length=100, early_stopping=True)
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    return summary

def lsa(text, n=1):
    # Create a pipeline to extract the latent topics
    pipeline = make_pipeline(
        TfidfVectorizer(),
        TruncatedSVD(n_components=n)
    )

    # Fit the pipeline to the text data and extract the top n topics
    pipeline.fit_transform([text])
    topics = pipeline.named_steps['truncatedsvd'].components_

    # Create the summary by selecting the top sentences based on the most important topics
    sentences = text.split('.')
    sentence_scores = []
    for i in range(len(sentences)):
        sentence_score = 0
        for j in range(n):
            sentence_score += abs(topics[j][i])
        sentence_scores.append((i, sentence_score))
    top_sentences = sorted(sentence_scores, key=lambda item: item[1], reverse=True)[:n]

    # Create the
    summary = ''
    for i in sorted([x[0] for x in top_sentences]):
        summary += sentences[i] + '.'

    return summary

def get_text_from_pdf(pdf_path):
    with open(pdf_path,'rb') as f:
        pdf = PyPDF2.PdfReader(f)
        text = ''
        for page in range(len(pdf.pages)):
            text += pdf.pages[page].extract_text()
        return text

class HomePageView(TemplateView):
    template_name = 'home.html'

class TextSummaryPageView(FormView):
    template_name = 'text_summary.html'
    success_url = '/text-summary/'
    form_class = TextSummaryForm

    def form_valid(self, form):
        text = form.cleaned_data['text_summary']
        nltk_summary = nltk_summarizer(text)
        sumy_summary = summy_summary(text)
        spacy_summary = spaacy_summary(text)
        t5_summary   = generate_summary(text)
        lsa_summary  = lsa(text)
        context      = self.get_context_data(form=form, 
                                             spacy_summary=spacy_summary,
                                             nltk_summary=nltk_summary,
                                             t5_summary=t5_summary,
                                             sumy_summary=sumy_summary,
                                             lsa_summary=lsa_summary
                                             )
        return self.render_to_response(context)
    
    
class PdfSummaryPageView(FormView):
    template_name = 'pdf_summary.html'
    success_url = '/pdf-summary/'
    form_class = PDFSummaryForm

    def form_valid(self, form):
        file = form.cleaned_data['pdf_summary']
        file_path = default_storage.save(file.name, file)
        file_url = self.request.scheme + '://' + self.request.get_host() + settings.MEDIA_URL + file_path
        text = get_text_from_pdf(f"media\\{file_path}")
        nltk_summary = nltk_summarizer(text)
        sumy_summary = summy_summary(text)
        spacy_summary = spaacy_summary(text)
        t5_summary   = generate_summary(text)
        lsa_summary  = lsa(text)
        context      = self.get_context_data(form=form, 
                                             spacy_summary=spacy_summary,
                                             nltk_summary=nltk_summary,
                                             t5_summary=t5_summary,
                                             sumy_summary=sumy_summary,
                                             lsa_summary=lsa_summary
                                             )
        return self.render_to_response(context)


class VideoSummaryPageView(TemplateView):
    template_name = 'video_summary.html'

class UrlSummaryPageView(TemplateView):
    template_name = 'url_summary.html'

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <title>{% block title %}{% endblock title %}</title>
    {% include 'snippets/head.html' %}
    {% block extra_head_url %}{% endblock extra_head_url %}   
</head>

<body>
    
    {% block content %}{% endblock content %}

    {% include 'snippets/scripts.html' %}
    {% block extra_script_url %}{% endblock extra_script_url %} 
    
</body>

</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>DotCom - Creative Agency Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Navbar Start -->
    <div class="container-fluid nav-bar p-0">
        <div class="container-lg p-0">
            <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
                <a href="index.html" class="navbar-brand">
                    <h1 class="m-0 text-white display-4"><span class="text-primary">D</span>ot<span class="text-primary">C</span>om</h1>
                </a>
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                    <div class="navbar-nav ml-auto py-0">
                        <a href="index.html" class="nav-item nav-link">Home</a>
                        <a href="about.html" class="nav-item nav-link">About</a>
                        <a href="service.html" class="nav-item nav-link">Services</a>
                        <a href="pricing.html" class="nav-item nav-link">Pricing</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu border-0 rounded-0 m-0">
                                <a href="blog.html" class="dropdown-item">Blog Grid</a>
                                <a href="single.html" class="dropdown-item">Blog Detail</a>
                            </div>
                        </div>
                        <a href="contact.html" class="nav-item nav-link active">Contact</a>
                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->


    <!-- Page Header Start -->
    <div class="container-fluid page-header d-flex flex-column align-items-center justify-content-center pt-0 pt-lg-5 mb-5">
        <h1 class="display-4 text-white mb-3 mt-0 mt-lg-5">Contact</h1>
        <div class="d-inline-flex text-white">
            <p class="m-0"><a class="text-white" href="">Home</a></p>
            <p class="m-0 px-2">/</p>
            <p class="m-0">Contact</p>
        </div>
    </div>
    <!-- Page Header Start -->


    <!-- Contact Start -->
    <div class="container-fluid py-5">
        <div class="container">
            <div class="text-center">
                <small class="bg-primary text-white text-uppercase font-weight-bold text-center px-1">Get In Touch</small>
                <h1 class="mt-2 mb-5">Contact For Any Queries</h1>
            </div>
            <div class="row">
                <div class="col-md-5">
                    <div class="d-flex align-items-center border mb-3 p-4">
                        <i class="fa fa-2x fa-map-marker-alt text-primary mr-3"></i>
                        <div class="d-flex flex-column">
                            <h5 class="font-weight-bold">Our Office</h5>
                            <p class="m-0">123 Street, New York, USA</p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center border mb-3 p-4">
                        <i class="fa fa-2x fa-envelope-open text-primary mr-3"></i>
                        <div class="d-flex flex-column">
                            <h5 class="font-weight-bold">Email Us</h5>
                            <p class="m-0">info@example.com</p>
                        </div>
                    </div>
                    <div class="d-flex align-items-center border mb-3 mb-md-0 p-4">
                        <i class="fas fa-2x fa-phone-alt text-primary mr-3"></i>
                        <div class="d-flex flex-column">
                            <h5 class="font-weight-bold">Call Us</h5>
                            <p class="m-0">+012 345 6789</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="contact-form">
                        <div id="success"></div>
                        <form name="sentMessage" id="contactForm" novalidate="novalidate">
                            <div class="form-row">
                                <div class="col-md-6">
                                    <div class="control-group">
                                        <input type="text" class="form-control p-4" id="name" placeholder="Your Name" required="required" data-validation-required-message="Please enter your name" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="control-group">
                                        <input type="email" class="form-control p-4" id="email" placeholder="Your Email" required="required" data-validation-required-message="Please enter your email" />
                                        <p class="help-block text-danger"></p>
                                    </div>
                                </div>
                            </div>
                            <div class="control-group">
                                <input type="text" class="form-control p-4" id="subject" placeholder="Subject" required="required" data-validation-required-message="Please enter a subject" />
                                <p class="help-block text-danger"></p>
                            </div>
                            <div class="control-group">
                                <textarea class="form-control" rows="5" id="message" placeholder="Message" required="required" data-validation-required-message="Please enter your message"></textarea>
                                <p class="help-block text-danger"></p>
                            </div>
                            <div>
                                <button class="btn btn-primary font-weight-semi-bold px-4" style="height: 50px;" type="submit" id="sendMessageButton">Send Message</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-white mt-5 pt-5 px-sm-3 px-md-5">
        <div class="row pt-5">
            <div class="col-lg-3 col-md-6 mb-5">
                <a href="index.html" class="navbar-brand">
                    <h1 class="m-0 mt-n2 text-white display-4"><span class="text-primary">D</span>ot<span class="text-primary">C</span>om</h1>
                </a>
                <p>Volup amet magna clita tempor. Tempor sea eos vero ipsum. Lorem lorem sit sed elitr sed kasd et</p>
                <div class="d-flex justify-content-start mt-4">
                    <a class="btn btn-outline-primary rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-primary rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-primary rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-primary rounded-circle text-center mr-2 px-0" style="width: 38px; height: 38px;" href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="font-weight-bold text-primary mb-4">Quick Links</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Home</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>About Us</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Services</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Pricing</a>
                    <a class="text-white" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="font-weight-bold text-primary mb-4">Popular Links</h5>
                <div class="d-flex flex-column justify-content-start">
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Home</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>About Us</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Services</a>
                    <a class="text-white mb-2" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Pricing</a>
                    <a class="text-white" href="#"><i class="fa fa-angle-right text-primary mr-2"></i>Contact Us</a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 mb-5">
                <h5 class="font-weight-bold text-primary mb-4">Get In Touch</h5>
                <p>Dolor clita stet nonumy clita diam vero, et et ipsum diam labore</p>
                <p><i class="fa fa-map-marker-alt text-primary mr-2"></i>123 Street, New York, USA</p>
                <p><i class="fa fa-phone-alt text-primary mr-2"></i>+012 345 67890</p>
                <p><i class="fa fa-envelope text-primary mr-2"></i>info@example.com</p>
            </div>
        </div>
    </div>
    <div class="container-fluid py-4 px-sm-3 px-md-5">
        <p class="m-0 text-center">
            &copy; <a class="font-weight-semi-bold" href="#">Your Site Name</a>. All Rights Reserved. Designed by
            <a class="font-weight-semi-bold" href="https://htmlcodex.com">HTML Codex</a>
        </p>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary back-to-top"><i class="fa fa-angle-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="lib/easing/easing.min.js"></script>
    <script src="lib/waypoints/waypoints.min.js"></script>
    <script src="lib/counterup/counterup.min.js"></script>
    <script src="lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="js/main.js"></script>
</body>

</html>

templates/snippets/footer.html
{% load static %}
 <!-- Footer Start -->
<div class="container-fluid text-white mt-5 pt-5 px-sm-3 px-md-5" style="position: absolute;bottom:0;height:100px;background-color:#131313;">
</div>

templates/snippets/head.html
{% load static %}
<meta charset="utf-8">
<meta content="width=device-width, initial-scale=1.0" name="viewport">
<meta content="Free HTML Templates" name="keywords">
<meta content="Free HTML Templates" name="description">

<!-- Favicon -->
<link href="{% static '' %}img/favicon.ico" rel="icon">

<!-- Google Web Fonts -->
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"> 

<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">

<!-- Libraries Stylesheet -->
<link href="{% static '' %}lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

<!-- Customized Bootstrap Stylesheet -->
<link href="{% static '' %}css/style.css" rel="stylesheet">

templates/snippets/header.html
{% load static %}
<!-- Navbar Start -->
<div class="container-fluid nav-bar p-0">
   <div class="container-lg p-0">
       <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
           <a href="/" class="navbar-brand">
               <h1 class="m-0 text-white display-4"><span class="text-primary"></span><span class="text-primary">S</span>ummary</h1>
           </a>
           <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
               <span class="navbar-toggler-icon"></span>
           </button>
           <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
               <div class="navbar-nav ml-auto py-0">
                   <a href="/" class="nav-item nav-link active">Home</a>
                   <a href="{% url 'summy:text'  %}" class="nav-item nav-link">Text</a>
                   <a href="{% url 'summy:pdf'   %}" class="nav-item nav-link">Pdf</a>
                   <a href="{% url 'summy:voice' %}" class="nav-item nav-link">Voice</a>
                   <a href="{% url 'summy:video' %}" class="nav-item nav-link">Video</a>
                   <a href="{% url 'summy:url'   %}" class="nav-item nav-link">Url</a>
               </div>
           </div>
       </nav>
   </div>
</div>
<!-- Navbar End -->

templates/snippets/header_pages.html
{% load static %}

<!-- Navbar Start -->
<div class="container-fluid nav-bar p-0 mb-5" style="top:0;position:fixed;background-color:#131313;">
    <div class="container-lg p-0">
        <nav class="navbar navbar-expand-lg bg-secondary navbar-dark">
            <a href="/" class="navbar-brand">
                <h1 class="m-0 text-white display-4"><span class="text-warning"></span><span class="text-warning">S</span>ummary</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                <div class="navbar-nav ml-auto py-0">
                    {% with request.resolver_match.url_name as url_name %}
                    <a href="/" class="nav-item nav-link {% if url_name == 'home'%} text-warning active {% else %} text-white {% endif %}">Home</a>
                    <a href="{% url 'summy:text'  %}" class="nav-item nav-link {% if url_name == 'text'%} text-warning active {% else %} text-white {% endif %}">Text</a>
                    <a href="{% url 'summy:pdf'   %}" class="nav-item nav-link {% if url_name == 'pdf'%} text-warning active {% else %} text-white {% endif %}">Pdf</a>
                    <a href="{% url 'summy:voice' %}" class="nav-item nav-link {% if url_name == 'voice'%} text-warning active {% else %} text-white {% endif %}">Voice</a>
                    <a href="{% url 'summy:video' %}" class="nav-item nav-link {% if url_name == 'video'%} text-warning active {% else %} text-white {% endif %}">Video</a>
                    <a href="{% url 'summy:url'   %}" class="nav-item nav-link {% if url_name == 'url'%} text-warning active {% else %} text-white {% endif %}">Url</a>
                    {% endwith %}
                </div>
            </div>
        </nav>
    </div>
</div>
    <!-- Navbar End -->

templates/snippets/loader.html
{% load static %}

templates/snippets/scripts.html
{% load static %}
<!-- JavaScript Libraries -->
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
<script src="{% static '' %}lib/easing/easing.min.js"></script>
<script src="{% static '' %}lib/waypoints/waypoints.min.js"></script>
<script src="{% static '' %}lib/counterup/counterup.min.js"></script>
<script src="{% static '' %}lib/owlcarousel/owl.carousel.min.js"></script>

<!-- Contact Javascript File -->
<script src="{% static '' %}mail/jqBootstrapValidation.min.js"></script>
<script src="{% static '' %}mail/contact.js"></script>

<!-- Template Javascript -->
<script src="{% static '' %}js/main.js"></script>

templates/snippets/slider.html
{% load static %}
<!-- Carousel Start -->
<div class="container-fluid p-0 mb-5">
    <div id="header-carousel" class="carousel slide carousel-fade" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
            <li data-target="#header-carousel" data-slide-to="1"></li>
            <li data-target="#header-carousel" data-slide-to="2"></li>
            <li data-target="#header-carousel" data-slide-to="3"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="img-fluid" src="{% static '' %}img/one.jpg" alt="Image" style="max-width:100%;height:100%">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Text</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="img-fluid" src="{% static '' %}img/carousel-2.jpg" alt="Image">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Video</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="img-fluid" src="{% static '' %}img/two.jpg" alt="Image">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Pdf</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="img-fluid" src="{% static '' %}img/carousel-3.jpg" alt="Image">
                <div class="carousel-caption d-flex align-items-center justify-content-center">
                    <div class="p-5" style="width: 100%; max-width: 900px;">
                        <h5 class="text-white text-uppercase mb-md-3 text-center">Our Project Can DO</h5>
                        <h1 class="display-3 text-white mb-md-4 text-center">Generate Summary For Voice</h1>
                        <h1 class="text-center"><a href="" class="btn btn-primary py-md-2 px-md-4 font-weight-semi-bold mt-2 mx-auto">Try Now</a></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Carousel End -->